import "../css/app.css";

import "./components/charts/daily-counter.js";
import "./components/charts/patient-summary.js";
import "./components/monitoring-branch.js";
import "./components/profile.js";
import "./components/clock.js";
import "./pages/header.js";
import "./pages/antrean_page.js";
import "./pages/views.js";
import "./pages/rekam_medis.js";
import "./pages/journal.js";
// import "./pages/antrean.js";
import "./pages/region.js";
import "./pages/transaksi.js";
import "./pages/users.js";
import "./pages/terapis.js";
import "./pages/detail_terapis.js";
import "./pages/complaint.js";
import "./pages/tag_rekam_medis.js";
import "./pages/tag_pemeriksaan.js";
