<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class TerapisSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'terapis_id'      => '004.071023',
                'nama'            => 'ANGGA NAHDIANSYAH',
                'tempat_lahir'    => 'BANYUMAS',
                'tanggal_lahir'   => '2000-07-07',
                'alamat'          => 'JL. ARSANTAKA, RT 02/RW 05, ARCAWINANGUN, PURWOKERTO',
                'region_id'       => 3,
                'jabatan_id'      => 9,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2023-11-07 16:42:50',
                'foto'            => '1730010288_WhatsApp_Image_2024-10-26_at_16_00_38.jpg',
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '002.010723',
                'nama'            => 'DIDIK IRMAWAN',
                'tempat_lahir'    => 'BANYUMAS',
                'tanggal_lahir'   => '1986-05-02',
                'alamat'          => 'JL KALIPUTIH RT 02 RW 01 PURWOKERTO TIMUR BANYUMAS',
                'region_id'       => 3,
                'jabatan_id'      => 1,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2023-07-01 14:46:51',
                'foto'            => '1730101611_WhatsApp_Image_2024-01-27_at_17_38_26.png',
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '003.011023',
                'nama'            => 'SLAMET YOGI SUGARA S.Kep',
                'tempat_lahir'    => 'BANJARNEGARA',
                'tanggal_lahir'   => '1995-04-26',
                'alamat'          => 'KRADENAN RT 03 RW 02 KRADENAN MREBET PURBALINGGA',
                'region_id'       => 20,
                'jabatan_id'      => 4,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2023-10-01 14:46:23',
                'foto'            => '1730101583_WhatsApp_Image_2024-01-27_at_17_47_03.jpg',
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '006.010324',
                'nama'            => 'RASMANTO',
                'tempat_lahir'    => 'BANYUMAS',
                'tanggal_lahir'   => '1971-04-09',
                'alamat'          => 'JL SUPRIYADI RT 04 RW 01 PURWOKERTO WETAN PURWOKERTO',
                'region_id'       => 3,
                'jabatan_id'      => 1,
                'rank'            => 'S',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-06-01 11:28:22',
                'foto'            => null,
                'is_active'       => 0,
            ],
            [
                'terapis_id'      => '007.010324',
                'nama'            => 'WARTAMAN',
                'tempat_lahir'    => 'BANYUMAS',
                'tanggal_lahir'   => '1969-04-04',
                'alamat'          => 'JL. PENATUSAN 1 NO 409 RT 02 RW 02 PURWOKERTO WETAN',
                'region_id'       => 3,
                'jabatan_id'      => 1,
                'rank'            => 'S',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-03-01 15:20:09',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '001.300123',
                'nama'            => 'ITA NAFSUL MUTMAINAH, S.Farm',
                'tempat_lahir'    => 'PURBALINGGA',
                'tanggal_lahir'   => '1995-07-09',
                'alamat'          => 'WALULU RT 02 RW 11 TUNJUNGMULI KARANGMONCOL PURBALINGGA',
                'region_id'       => 3,
                'jabatan_id'      => 6,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2023-01-30 15:38:41',
                'foto'            => '1730018321_Ita_Nafsul_Mutmainah_S__Farm.JPG',
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '008.010524',
                'nama'            => 'AHMAD DAVID HERMANTO',
                'tempat_lahir'    => 'BATANG',
                'tanggal_lahir'   => '1985-01-20',
                'alamat'          => 'CANDI GUGUR RT 01 RW 01 BAWANG BATANG',
                'region_id'       => 2,
                'jabatan_id'      => 1,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-05-01 15:22:15',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '018.010524',
                'nama'            => 'I MADE MAHARDIKA',
                'tempat_lahir'    => 'PEKALONGAN',
                'tanggal_lahir'   => '1984-07-31',
                'alamat'          => 'DUKUH KLAWEN RT 17 RW 07 CANDIGUGUR BAWANG BATANG',
                'region_id'       => 22,
                'jabatan_id'      => 4,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-05-01 15:39:27',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '022.010724',
                'nama'            => 'AKBAR BAHAULLOH',
                'tempat_lahir'    => 'CILACAP',
                'tanggal_lahir'   => '1991-07-25',
                'alamat'          => 'JL DESA KEMUTUG LOR RT 04 RW 01 KEMUTUG LOR BATURRADEN',
                'region_id'       => 23,
                'jabatan_id'      => 7,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-07-01 16:34:52',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '023.130824',
                'nama'            => 'AGUS MUKHOTIM',
                'tempat_lahir'    => 'CILACAP',
                'tanggal_lahir'   => '1992-08-30',
                'alamat'          => 'DUSUN CIKLAPA RT 06 RW 01 CIKLAPA KEDUNGREJA CILACAP',
                'region_id'       => 23,
                'jabatan_id'      => 1,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-08-13 15:28:55',
                'foto'            => '1730017735_WhatsApp_Image_2024-10-27_at_14_07_22.jpg',
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '024.130824',
                'nama'            => 'DEDE SUGIYONO',
                'tempat_lahir'    => 'CILACAP',
                'tanggal_lahir'   => '1992-08-25',
                'alamat'          => 'DUSUN RAWAAPU RT 01 RW 08 RAWAAPU PAIMUAN CILACAP',
                'region_id'       => 23,
                'jabatan_id'      => 1,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-08-13 15:30:10',
                'foto'            => '1730017810_WhatsApp_Image_2024-10-27_at_14_07_22.jpg',
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '025.130824',
                'nama'            => 'TATI NUR FATMAH',
                'tempat_lahir'    => 'CILACAP',
                'tanggal_lahir'   => '1999-11-16',
                'alamat'          => 'DUSUN GEBANGSARI RT 07 RW 03 TAMBAKSARI KEDUNGREJA CILACAP',
                'region_id'       => 23,
                'jabatan_id'      => 5,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-08-13 15:31:25',
                'foto'            => '1730017885_WhatsApp_Image_2024-10-27_at_14_08_59.jpg',
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '027.010924',
                'nama'            => 'SLAMET RIADI',
                'tempat_lahir'    => 'BANYUMAS',
                'tanggal_lahir'   => '1972-06-19',
                'alamat'          => 'KARANGNANGKA RT 01 RW 05 KARANGNANGKA KEDUNG BANTENG BANYUMAS',
                'region_id'       => 3,
                'jabatan_id'      => 3,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-06-01 11:28:36',
                'foto'            => '1733224801_foto_pak_slamet.jpg',
                'is_active'       => 0,
            ],
            [
                'terapis_id'      => '028.011024',
                'nama'            => 'TONI MUSTOFA',
                'tempat_lahir'    => 'CILACAP',
                'tanggal_lahir'   => '1993-01-11',
                'alamat'          => 'DUSUN WARUREJA RT 05 RW 03 MARGASARI SIDAREJA CILACAP',
                'region_id'       => 23,
                'jabatan_id'      => 3,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-11-18 17:27:06',
                'foto'            => '1730018282_WhatsApp_Image_2024-10-27_at_14_07_32.jpg',
                'is_active'       => 0,
            ],
            [
                'terapis_id'      => '029.010424',
                'nama'            => 'MUHAMMAD ILYAS',
                'tempat_lahir'    => 'WONOSOBO',
                'tanggal_lahir'   => '2001-10-16',
                'alamat'          => 'JL KALIPUTIH RT 02 RW 01 PURWOKERTO TIMUR PURWOKERTO',
                'region_id'       => 3,
                'jabatan_id'      => 8,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-04-01 15:43:33',
                'foto'            => '1730018444_WhatsApp_Image_2024-10-27_at_15_39_41.jpg',
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '030.131024',
                'nama'            => 'TOFIK HIDAYAT',
                'tempat_lahir'    => 'BANYUMAS',
                'tanggal_lahir'   => '1985-04-10',
                'alamat'          => 'REMPOAH RT 01 RW 06 REMPOAH BATURRADEN BANYUMAS',
                'region_id'       => 3,
                'jabatan_id'      => 3,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-06-01 11:28:50',
                'foto'            => '1733224764_foto_mas_tofik.jpg',
                'is_active'       => 0,
            ],
            [
                'terapis_id'      => '034.230924',
                'nama'            => 'IRMA SETIANI, S.Pd',
                'tempat_lahir'    => 'PURBALINGGA',
                'tanggal_lahir'   => '2002-03-21',
                'alamat'          => 'PURBALINGGA',
                'region_id'       => 3,
                'jabatan_id'      => 5,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-09-23 16:53:10',
                'foto'            => '1745747590_cow_wallpaper.jpg',
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '013.010524',
                'nama'            => 'ADE SEPTIAWAN',
                'tempat_lahir'    => 'PURBALINGGA',
                'tanggal_lahir'   => '1991-09-08',
                'alamat'          => 'J. PURNAWARMAN BARAT RT 11 RW 02 SINDANGKASIH PURWAKARTA',
                'region_id'       => 24,
                'jabatan_id'      => 1,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-05-01 13:18:21',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '014.010524',
                'nama'            => 'DWI SEPTIADI',
                'tempat_lahir'    => 'PURBALINGGA',
                'tanggal_lahir'   => '1994-09-03',
                'alamat'          => 'SIDAKANGEN RT 01 RW 01 SIDAKANGEN KALIMANAH PURBALINGGA',
                'region_id'       => 20,
                'jabatan_id'      => 1,
                'rank'            => 'S',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-05-01 13:19:24',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '020.010524',
                'nama'            => 'EGA SEPTININGSIH',
                'tempat_lahir'    => 'PURBALINGGA',
                'tanggal_lahir'   => '1999-04-09',
                'alamat'          => 'KRADENAN RT 03 RW 02 KRADENAN MREBET PURBALINGGA',
                'region_id'       => 20,
                'jabatan_id'      => 5,
                'rank'            => 'S',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-05-01 13:20:10',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '031.051024',
                'nama'            => 'IMAM SETIAWAN',
                'tempat_lahir'    => 'PURBALINGGA',
                'tanggal_lahir'   => '1989-10-15',
                'alamat'          => 'BOJONG RT 01 RW 04 BOJONG MREBER PURBALINGGA',
                'region_id'       => 20,
                'jabatan_id'      => 3,
                'rank'            => 'S',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-10-05 13:25:17',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '032.051024',
                'nama'            => 'KOKO PRIAMBODO',
                'tempat_lahir'    => 'PURWOKERTO',
                'tanggal_lahir'   => '1984-10-23',
                'alamat'          => 'TOYAREKA RT 02 RW 10 TOYAREKA KEMANGKON PURBALINGGA',
                'region_id'       => 24,
                'jabatan_id'      => 3,
                'rank'            => 'S',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-10-05 13:26:34',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '033.121024',
                'nama'            => 'LIANA DWI LESTARI',
                'tempat_lahir'    => 'PURBALINGGA',
                'tanggal_lahir'   => '1994-11-09',
                'alamat'          => 'SURAJAYA RT 01 RW 06 SURAJAYA PEMALANG',
                'region_id'       => 24,
                'jabatan_id'      => 5,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-10-12 17:37:37',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '026.150824',
                'nama'            => 'ISHADI IMDADIN',
                'tempat_lahir'    => 'BATANG',
                'tanggal_lahir'   => '1984-06-23',
                'alamat'          => 'JL. SUNAN AMPEL RT 13 RW 04 BAWANG BATANG',
                'region_id'       => 22,
                'jabatan_id'      => 1,
                'rank'            => 'S',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-08-15 13:31:12',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '010.010524',
                'nama'            => 'ARIF ZAFRAN SETIAWAN',
                'tempat_lahir'    => 'TEMANGGUNG',
                'tanggal_lahir'   => '1991-04-24',
                'alamat'          => 'DUSUN DIWEK RT 05 RW 07 BOJONEGORO KEDU TEMANGGUNG',
                'region_id'       => 19,
                'jabatan_id'      => 1,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-05-01 17:37:53',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '035.081276',
                'nama'            => 'ARIF GUNAWAN RAHARJO',
                'tempat_lahir'    => 'PURWOKERTO',
                'tanggal_lahir'   => '1976-12-08',
                'alamat'          => 'JL. PRAMUKA RT 01 RW 02 SUDAGARAN BANYUMAS',
                'region_id'       => 7,
                'jabatan_id'      => 3,
                'rank'            => 'B',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-10-01 09:35:28',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '036.111124',
                'nama'            => 'BAYU APRIADI',
                'tempat_lahir'    => 'CILACAP',
                'tanggal_lahir'   => '2003-03-27',
                'alamat'          => 'JL. KENDENG RT 008 RW 015 KELURAHAN SIDANEGARA KECAMATAN CILACAP',
                'region_id'       => 7,
                'jabatan_id'      => 3,
                'rank'            => 'B',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-11-11 11:21:13',
                'foto'            => '1738470073_WhatsApp_Image_2025-02-02_at_11_19_50.jpg',
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '037.201024',
                'nama'            => 'IMAM MAULANA',
                'tempat_lahir'    => 'PEKALONGAN',
                'tanggal_lahir'   => '1985-05-25',
                'alamat'          => 'KERTAYASA RT 06 RW 01 KERTAYASA KRAMAT TEGAL',
                'region_id'       => 28,
                'jabatan_id'      => 1,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-10-20 19:23:04',
                'foto'            => '1735474127_WhatsApp_Image_2024-12-29_at_19_06_30.jpg',
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '038.271024',
                'nama'            => 'FAHRUROZI',
                'tempat_lahir'    => 'BATANG',
                'tanggal_lahir'   => '2024-10-27',
                'alamat'          => 'DESA CANDI GUGUR RT 02 RW 02 CANDIGUGUR BAWANG BATANG',
                'region_id'       => 28,
                'jabatan_id'      => 1,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-10-27 19:22:23',
                'foto'            => '1735474160_WhatsApp_Image_2024-12-29_at_19_06_29.jpg',
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '039.260125',
                'nama'            => 'DANI JAMALUDIN',
                'tempat_lahir'    => 'TASIKMALAYA',
                'tanggal_lahir'   => '1978-10-27',
                'alamat'          => 'CANTIGI RT 02 RW 08 CISAYONG TASIKMALAYA',
                'region_id'       => 27,
                'jabatan_id'      => 5,
                'rank'            => 'B',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-01-26 09:47:22', // Data sebelumnya 0000, saya sesuaikan agar valid
                'foto'            => null,
                'is_active'       => 1,
            ],

            [
                'terapis_id'      => '040.260125',
                'nama'            => 'DIDIN WAHYUDIN',
                'tempat_lahir'    => 'TASIKMALAYA',
                'tanggal_lahir'   => '1978-09-28',
                'alamat'          => 'KP CIRANDO RT 02 RW 09 CIASAYONG TASIKMALAYA',
                'region_id'       => 27,
                'jabatan_id'      => 1,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-01-26 09:47:22',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '041.260125',
                'nama'            => 'DAYU SUKMARA',
                'tempat_lahir'    => 'TASIKMALAYA',
                'tanggal_lahir'   => '2000-10-06',
                'alamat'          => 'KP GIRIMUKTI RT 04 RW 04 SUKAJADI CISAYONG TASIKMALAYA',
                'region_id'       => 27,
                'jabatan_id'      => 1,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-01-26 09:48:34',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '043.181124',
                'nama'            => 'INTAN NORMALITA',
                'tempat_lahir'    => 'PURBALINGGA',
                'tanggal_lahir'   => '1999-06-26',
                'alamat'          => 'PAGEDANGAN RT 12 RW 06, PAGEDANGANM BOJONGSARI',
                'region_id'       => 20,
                'jabatan_id'      => 5,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-10-01 11:29:20',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '044.150125',
                'nama'            => 'TUHAINUN',
                'tempat_lahir'    => 'PEMALANG',
                'tanggal_lahir'   => '1991-11-06',
                'alamat'          => 'DESA JATIMULYO, PETARUKAN RT 02 RW 04, PETARUKAN',
                'region_id'       => 24,
                'jabatan_id'      => 1,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2026-03-28 09:13:24',
                'foto'            => null,
                'is_active'       => 0,
            ],
            [
                'terapis_id'      => '042.301124',
                'nama'            => 'GOVINDA ASVA YUHANNA',
                'tempat_lahir'    => 'BATANG',
                'tanggal_lahir'   => '1995-12-24',
                'alamat'          => 'JL. SUNAN KALIJAGA RT 14 RW 04, BAWANG',
                'region_id'       => 22,
                'jabatan_id'      => 1,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-11-20 11:31:16',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '045.130225',
                'nama'            => 'JINI MUNSAROH',
                'tempat_lahir'    => 'BANYUMAS',
                'tanggal_lahir'   => '2005-06-03',
                'alamat'          => 'BOJONGSARI RT 03 RW 08, BOJONGSARI, KEMBARAN',
                'region_id'       => 3,
                'jabatan_id'      => 1,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-02-13 14:55:16',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '046.130225',
                'nama'            => 'LIA WIDYA SANTI',
                'tempat_lahir'    => 'PEKALONGAN',
                'tanggal_lahir'   => '1996-12-07',
                'alamat'          => 'KEDUNGPATANGEWU RT 09 RW 05 KEDUNGWUNI PEKALONGAN',
                'region_id'       => 28,
                'jabatan_id'      => 5,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-02-13 11:43:46',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '047.190425',
                'nama'            => 'DINDA AYU PARADITA',
                'tempat_lahir'    => 'BATANG',
                'tanggal_lahir'   => '2002-07-08',
                'alamat'          => 'TEGALOMBO RT 02 RW 01 TEGALOMBO TERSONO, BATANG',
                'region_id'       => 22,
                'jabatan_id'      => 5,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-04-19 11:34:49',
                'foto'            => null,
                'is_active'       => 0,
            ],
            [
                'terapis_id'      => '049.230425',
                'nama'            => 'BUDI SANTOSO',
                'tempat_lahir'    => 'BANTUL',
                'tanggal_lahir'   => '1980-08-16',
                'alamat'          => 'KALANGAN RT 17 RW 00 BATURETNO BANGUNTAPAN',
                'region_id'       => 29,
                'jabatan_id'      => 1,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-04-23 12:21:19',
                'foto'            => null,
                'is_active'       => 1,
            ],

            [
                'terapis_id'      => '048.230425',
                'nama'            => 'SUROYO',
                'tempat_lahir'    => 'GUNUNGKIDUL',
                'tanggal_lahir'   => '1977-08-13',
                'alamat'          => 'SANDEYAN RT 05 RW 00, SRIMULYO PIYUNGAN',
                'region_id'       => 29,
                'jabatan_id'      => 1,
                'rank'            => 'S',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2026-03-28 08:58:20',
                'foto'            => null,
                'is_active'       => 0,
            ],
            [
                'terapis_id'      => '050.161124',
                'nama'            => 'GUSTI IKHLAS PASHA',
                'tempat_lahir'    => 'BANYUMAS',
                'tanggal_lahir'   => '2002-11-09',
                'alamat'          => 'JL. KARANGKOBAR GG 4 RT 03 RW 08, SOKANEGARA, PURWOKERTO',
                'region_id'       => 3,
                'jabatan_id'      => 5,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2024-11-16 12:47:33',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '051.100525',
                'nama'            => 'SURYO GIHANTORO',
                'tempat_lahir'    => 'PURBALINGGA',
                'tanggal_lahir'   => '1987-11-30',
                'alamat'          => 'KRADENAN RT 01 RW 03 KRADENAN MREBET PURBALINGGA',
                'region_id'       => 20,
                'jabatan_id'      => 1,
                'rank'            => 'S',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-05-10 12:31:10',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '052.100625',
                'nama'            => 'LELYANA MEINAWATI',
                'tempat_lahir'    => 'WONOSOBO',
                'tanggal_lahir'   => '1987-05-03',
                'alamat'          => 'POJOKSARI RT 06 RW 01, POJOKSARI, AMBARAWA',
                'region_id'       => 7,
                'jabatan_id'      => 5,
                'rank'            => 'SS',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-06-10 12:32:19',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '053.080625',
                'nama'            => 'ISWAHYUDI PURNOMO',
                'tempat_lahir'    => 'CILACAP',
                'tanggal_lahir'   => '1994-01-26',
                'alamat'          => 'JL. SALYA RT 02 RW 03, GUMILIR, CILACAP UTARA',
                'region_id'       => 7,
                'jabatan_id'      => 1,
                'rank'            => 'S',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-06-08 16:03:04',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '054.170725',
                'nama'            => 'ACHMAD NURDIAN YUDISTIRO',
                'tempat_lahir'    => 'PEMALANG',
                'tanggal_lahir'   => '1995-06-25',
                'alamat'          => 'DESA KALIRANDU RT 07 RW 05, KALIRANDU, PETARUKAN',
                'region_id'       => 24,
                'jabatan_id'      => 1,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-07-17 12:33:58',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '055.190725',
                'nama'            => 'SUSI SRI LESTARI',
                'tempat_lahir'    => 'SLEMAN',
                'tanggal_lahir'   => '2002-02-12',
                'alamat'          => 'KERINGAN LOR RT 03 RW 06, BULUREJO, SEMIN',
                'region_id'       => 29,
                'jabatan_id'      => 5,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-07-19 17:24:45',
                'foto'            => null,
                'is_active'       => 0,
            ],
            [
                'terapis_id'      => '056.240725',
                'nama'            => 'WIDIYA WAHYUNINGRUM',
                'tempat_lahir'    => 'KUDUS',
                'tanggal_lahir'   => '2003-12-25',
                'alamat'          => 'KARANGROWO RT 03 RW 02, KARANGROWO, UNDAAN',
                'region_id'       => 22,
                'jabatan_id'      => 5,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-07-24 12:35:26',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '123',
                'nama'            => 'PAK OTO',
                'tempat_lahir'    => 'BANYUMAS',
                'tanggal_lahir'   => '1965-05-31',
                'alamat'          => 'SOKANEGARA',
                'region_id'       => 14,
                'jabatan_id'      => 3,
                'rank'            => '',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-11-15 15:55:36',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '057.151125',
                'nama'            => 'MUHAMMAD RIZKY ARIADI',
                'tempat_lahir'    => 'BREBES',
                'tanggal_lahir'   => '1997-02-03',
                'alamat'          => 'DK KRAJAN II, RT 01 RW 03, JATISAWIT, BUMIAYU, BREBES',
                'region_id'       => 31,
                'jabatan_id'      => 1,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2026-01-19 15:45:15',
                'foto'            => null,
                'is_active'       => 0,
            ],
            [
                'terapis_id'      => '058.181125',
                'nama'            => 'WAHYU ALAMSYAH',
                'tempat_lahir'    => 'BREBES',
                'tanggal_lahir'   => '1999-08-21',
                'alamat'          => 'BAROS RT 01 RW 04, BAROS, KETANGGUNGAN, BREBES',
                'region_id'       => 31,
                'jabatan_id'      => 1,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-11-18 18:45:11',
                'foto'            => null,
                'is_active'       => 1,
            ],
            [
                'terapis_id'      => '059.011225',
                'nama'            => 'ANGGA NURWIYANTO',
                'tempat_lahir'    => 'PURBALINGGA',
                'tanggal_lahir'   => '1999-07-06',
                'alamat'          => 'ONJE RT 01 RW 02, ONJE, MREBET, PURBALINGGA',
                'region_id'       => 5,
                'jabatan_id'      => 1,
                'rank'            => 'A',
                'keterangan'      => '',
                'tgl_mulai_kerja' => '2025-12-01 15:47:42',
                'foto'            => null,
                'is_active'       => 1,
            ],
        ];

        $this->db->table('terapis')->insertBatch($data);
    }
}
